### ISSUE TITLE
Add page for 404 error code

### ISSUE THREAD

**Issue by gomzyakov** [github-profile-achievements/github-profile-achievements.github.io#15]
Like in https://github.com/good-first-issues/good-first-issues.github.io/pull/50

**Comment by ShadBalti** [comment]
Assigned me

**Comment by gomzyakov** [comment]
@ShadBalti Hello!

Assigned to you ;)

**Comment by ShadBalti** [comment]
Hello! Thanks for assigning this to me. I'll start working on adding a page for the 404 error code (#15) and will keep you updated on my progress.
